name: CD Pipeline - Deploy a GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar en GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy a Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: video-game-api
          region: us-central1
          source: .
