name: CI Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend/HUB_GAMES

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # He actualizado esto a 22 porque tu package.json dice >=22.12.0

      - name: Instalar dependencias
        run: npm install

      # Hemos eliminado el paso de tests porque no existen en tu proyecto
      
      - name: Ejecutar Build de Astro
        run: npm run build

      - name: Build exitoso
        run: echo "El proyecto Astro se ha compilado correctamente en frontend/HUB_GAMES"
